services:
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass    
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend: