version: "3"

tasks:
  # separate bin format
  build:
    cmds:
      - go build -o ./out/server
  run:
    cmds:
      - task: build
      - ./out/server
  
  seed:
    cmds:
    - go run ./scripts/main.go

  test:
    cmds:
    - go test -v -count=1 -race ./tests
  # add commit message as parameter
  vcs:
    cmds:
      - git add .
      - git commit -m "update"
      - git push -u https://github.com/Cassanl/HotelRes.git main
