version: '3'

tasks:
  # separate bin format
  build:
    cmds: 
    - go build -o ./out/server.exe
  run:
    cmds:
    - task: build
    - ./out/server.exe
  
  # add commit message as parameter
  # needs PAT https://[PAT]@github.com/Cassanl/HotelRes.git
  vcs: 
    cmds:
      - git add .
      - git commit -m "update"
      - git push -u https://github.com/Cassanl/HotelRes.git main